[program:hr-scheduler]
command=/bin/bash -lc 'while true; do php /var/www/hr/current/artisan schedule:run --verbose --no-interaction; sleep 60; done'
directory=/var/www/hr/current
autostart=true
autorestart=true
numprocs=1
process_name=%(program_name)s
user=www-data
redirect_stderr=true
stdout_logfile=/var/log/supervisor/hr-scheduler.log
