[program:hr-worker]
command=php /var/www/hr/current/artisan queue:work redis --queue=high,default,low --sleep=1 --tries=3 --timeout=120
directory=/var/www/hr/current
autostart=true
autorestart=true
numprocs=3
process_name=%(program_name)s_%(process_num)02d
user=www-data
redirect_stderr=true
stdout_logfile=/var/log/supervisor/hr-worker.log
stopwaitsecs=360
