@extends('layouts.app')
@section('content')
<div class="content-wrapper">
    <div class="d-flex justify-content-between mb-2"><h4>HR compliance</h4><a class="btn btn-light" href="{{ route('hr-certification-rules.index') }}">Certification rules</a></div>
    <div class="card"><div class="card-body">
        <form method="POST" action="{{ route('hr-compliance.probation') }}">@csrf<select name="employee_id">@foreach($employees as $employee)<option value="{{ $employee->id }}">{{ $employee->name }}</option>@endforeach</select><select name="review_day"><option>30</option><option>60</option><option>90</option></select><input type="date" name="due_date" required><button>Save probation review</button></form><hr>
        <form method="POST" action="{{ route('hr-compliance.certification') }}">@csrf<select name="employee_id">@foreach($employees as $employee)<option value="{{ $employee->id }}">{{ $employee->name }}</option>@endforeach</select><input name="name" placeholder="Certification" required><input type="date" name="expires_at"><button>Save certification</button></form><hr>
        <form method="POST" action="{{ route('hr-compliance.case') }}">@csrf<input name="category" placeholder="Restricted case category" required><input name="details" placeholder="Confidential details" required><button>Create restricted case</button></form>
    </div></div>
    <div class="card mt-3"><div class="card-body"><h5>Document expiry dashboard</h5>
        <form method="GET" class="form-inline mb-3"><select class="form-control mr-2" name="expiry_band"><option value="all">All bands</option>@foreach(['expired','0-30','31-60','61-90'] as $band)<option value="{{ $band }}" @selected($expiryBand === $band)>{{ $band }}</option>@endforeach</select><select class="form-control mr-2" name="expiry_type"><option value="all">All documents</option>@foreach(['passport','iqama','insurance','contract'] as $type)<option value="{{ $type }}" @selected($expiryType === $type)>{{ ucfirst($type) }}</option>@endforeach</select><button class="btn btn-secondary">Filter</button></form>
        <table class="table"><thead><tr><th>Employee</th><th>Document</th><th>Expiry</th><th>Band</th></tr></thead><tbody>@forelse($expiryItems as $item)<tr><td>{{ $item['employee']->name }}</td><td>{{ $item['label'] }}</td><td>{{ $item['date']->format('Y-m-d') }}</td><td><span class="badge badge-{{ $item['band'] === 'expired' ? 'danger' : 'warning' }}">{{ $item['band'] }}</span></td></tr>@empty<tr><td colspan="4">No documents in the selected expiry band.</td></tr>@endforelse</tbody></table>
    </div></div>
    @if($requiredCertificationGaps->isNotEmpty())<div class="card mt-3 border-warning"><div class="card-body"><h5>Missing required certifications</h5><p class="text-muted">Requirements are matched by company and designation. Add or renew a certification to clear the gap.</p>@foreach($requiredCertificationGaps as $gap)<div>{{ $gap['employee']->name }} — {{ $gap['requirements']->implode(', ') }}</div>@endforeach</div></div>@endif
    <div class="card mt-3"><div class="card-body">
        <h5>Probation reviews</h5>@foreach($reviews as $review)<div>{{ $review->employee->name }} — day {{ $review->review_day }} — {{ $review->status }}<form class="d-inline" method="POST" action="{{ route('hr-compliance.probation.complete',$review) }}">@csrf<select name="status"><option value="confirmed">Confirm</option><option value="extended">Extend</option><option value="completed">Complete</option></select><input name="notes" placeholder="Review notes"><button>Save</button></form></div>@endforeach
        <h5 class="mt-3">Certifications</h5>@foreach($certifications as $certification)<div>{{ $certification->employee->name }} — {{ $certification->name }} — {{ $certification->expires_at?->format('Y-m-d') }}<form class="d-inline" method="POST" action="{{ route('hr-compliance.certification.renew',$certification) }}">@csrf<input type="date" name="expires_at" required><button>Renew</button></form></div>@endforeach
        <h5 class="mt-3">Restricted cases</h5>@foreach($cases as $case)<div>{{ $case->category }} — {{ $case->status }}<form class="d-inline" method="POST" action="{{ route('hr-compliance.case.update',$case) }}">@csrf<select name="status"><option>open</option><option>in_review</option><option>closed</option></select><button>Update</button></form></div>@endforeach
    </div></div>
</div>
@endsection
