@extends('layouts.app')

@section('content')
    <div class="content-wrapper">
    <div class="d-flex justify-content-between mb-3"><h4>{{ $employee->name }}</h4><a class="btn btn-light" href="{{ route('employees.show', $employee->id) }}">Employee profile</a></div>
    <div class="row">
        <div class="col-md-6"><div class="card"><div class="card-body"><h5>Onboarding</h5>@if($onboarding)<span class="badge badge-info">{{ $onboarding->status }}</span>@foreach($onboardingTasks as $task)<form class="mt-2" method="POST" action="{{ route('hr-lifecycle.tasks.update', ['onboarding', $task->id]) }}">@csrf<label><input type="checkbox" name="complete" value="1" onchange="this.form.submit()" {{ $task->status === 'completed' ? 'checked' : '' }}> {{ $task->title }} <small>{{ $task->due_date }}</small></label></form>@endforeach<form class="form-inline mt-2" method="POST" action="{{ route('hr-lifecycle.tasks.add', ['onboarding', $onboarding->id]) }}">@csrf<input class="form-control form-control-sm mr-1" name="title" placeholder="Add task" required><input class="form-control form-control-sm mr-1" type="date" name="due_date"><button class="btn btn-sm btn-light">Add</button></form> @else<form method="POST" action="{{ route('hr-lifecycle.onboarding.start', $employee->id) }}">@csrf<button class="btn btn-primary">Start onboarding</button></form>@endif</div></div></div>
        <div class="col-md-6"><div class="card"><div class="card-body"><h5>Offboarding</h5>@if($offboarding)<span class="badge badge-warning">{{ $offboarding->status }}</span>@foreach($offboardingTasks as $task)<form class="mt-2" method="POST" action="{{ route('hr-lifecycle.tasks.update', ['offboarding', $task->id]) }}">@csrf<label><input type="checkbox" name="complete" value="1" onchange="this.form.submit()" {{ $task->status === 'completed' ? 'checked' : '' }}> {{ $task->title }} <small>{{ $task->due_date }}</small></label></form>@endforeach<form class="form-inline mt-2" method="POST" action="{{ route('hr-lifecycle.tasks.add', ['offboarding', $offboarding->id]) }}">@csrf<input class="form-control form-control-sm mr-1" name="title" placeholder="Add task" required><input class="form-control form-control-sm mr-1" type="date" name="due_date"><button class="btn btn-sm btn-light">Add</button></form> @else<form method="POST" action="{{ route('hr-lifecycle.offboarding.start', $employee->id) }}">@csrf<input class="form-control mb-2" name="reason" placeholder="Reason" required><input class="form-control mb-2" type="date" name="last_working_date" required><button class="btn btn-danger">Start offboarding</button></form>@endif</div></div></div>
    </div>
    <div class="card mt-3"><div class="card-body"><h5>Branch transfer</h5><form method="POST" action="{{ route('hr-lifecycle.transfer.request', $employee->id) }}" class="form-inline">@csrf<select class="form-control mr-2" name="to_branch_id" required>@foreach($branches as $branch)<option value="{{ $branch->id }}">{{ $branch->name }}</option>@endforeach</select><input class="form-control mr-2" type="date" name="effective_date" required><input class="form-control mr-2" name="reason" placeholder="Reason"><button class="btn btn-primary">Request transfer</button></form>@foreach($transfers as $transfer)<div class="mt-2">{{ $transfer->effective_date->format('Y-m-d') }} — {{ $transfer->status }} @if($transfer->status === 'pending' && in_array('admin', user_roles()))<form class="d-inline" method="POST" action="{{ route('hr-lifecycle.transfer.approve', $transfer->id) }}">@csrf<button class="btn btn-sm btn-success">Approve</button></form>@endif @if($transfer->status === 'approved' && in_array('admin', user_roles()) && !$transfer->effective_date->isFuture())<form class="d-inline" method="POST" action="{{ route('hr-lifecycle.transfer.apply', $transfer->id) }}">@csrf<button class="btn btn-sm btn-primary">Apply</button></form>@endif</div>@endforeach</div></div>
    </div>
@endsection
